### ISSUE TITLE
'modder --help' throws error

### ISSUE THREAD

**Issue by Dhyfer1** [KuhakuPixel/AceTheGame#90]
Hi dev.

My phone is not rooted, and I have followed the steps correctly for setting up the ModderRelease.zip file as you show in the tutorial video.

But when I run the `modder --help` command I get the following error:

```cmd

C:\Users\diego>modder --help
Exception in thread "main" java.lang.Unsupported ClassVersionError: modder/Main has been compiled by a more recent version of the Java Runtime (class 
 file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) 
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source) 
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged (Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source) 
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source) 
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

C:\Users\diego>>
```

I have installed the latest version of Java Runtime Environment 8u401. I am using Windows 11 64bits, the JAVA_HOME system variable( is created correctly.

I don't understand why I get this error, I followed the steps in the video correctly.

**Comment by cns00** [comment]
I actually just had the same issue and I solved it. The Java Runtime Environment that you have can only run up to class version 52 and it doesn't matter if you have the latest version of Java Runtime Environment installed. You have to install JDK Development kit which you can get from https://www.oracle.com/java/technologies/downloads/#jdk21-windows. JDK Development kit can run class version 61. I installed JDK Development kit and I was able to run modder.
